// Czech descriptions for the remaining 98 GVS Cosmetics products (the 20 most
// relevant ones are in set-gvs-descriptions.ts). Written 2026-10-09 in our own
// words from the brands' catalogs (doctoraltheaglobal.com, vvbetter.com), K-beauty
// retailers (kosmosbeauty.com, nudieglow.com, olivekollection.com, saranghae.ch,
// cosmeterie.com) and the supplier's own Czech copy — facts only, no medical
// claims; usage only where a source states it. Size variants of one product line
// share the text and differ in the size bullet; the damaged-packaging (DEFECT)
// copies keep their notice and get the same text as the regular product.
//
// Usage: npx tsx scripts/set-gvs-descriptions-rest.ts --dry-run | (no flag = apply)
import { prisma } from "../src/lib/prisma";
import { logAdminActivity } from "../src/lib/admin/activity-log";

const DRY_RUN = process.argv.includes("--dry-run");

const TEXTS: Record<string, string> = {
  "GVS-10179": "<p>Oplachový kondicionér s malinovým octem od CP-1 pro matné, poškozené a unavené vlasy. Šampony bývají zásadité, což může vést k vysušené pokožce hlavy a ztrátě lesku. Mírně kyselý oplach (pH 5,5) rovnováhu vrací, vlasy zbavuje zbytků šamponu a dodává jim hebkost a lesk.</p><ul><li>objem 500 ml</li><li>pH 5,5, slabě kyselé složení</li><li>vyhlazuje vlasy a vrací jim lesk</li></ul><p><strong>Použití:</strong> Používá se po šamponování jako oplach nebo kondicionér.</p>",
  "GVS-10230": "<p>Koncentrovaná keratinová esence CP-1 pro suché, lámavé a krepovité vlasy. Pomáhá udržet správnou hladinu vlhkosti, vrací vlasům pružnost a lesk, opravuje poškozená místa a předchází roztřepeným konečkům. Lehká textura připomíná odtučněný olej, takže vlasy nezatěžuje. Obsahuje keratin, extrakt z listů baobabu a elastin a je bez sulfátů.</p><ul><li>objem 80 ml</li><li>esence pro suché, lámavé a krepovité vlasy</li><li>bez sulfátů</li></ul>",
  "GVS-10551": "<p>Proteinová maska CP-1 Premium Hair Treatment pro namáhané vlasy: suché, lámavé, odbarvené i poškozené teplem či chemií. Hedvábný protein a keramidy pomáhají vlasy vyplnit zevnitř a zpevnit roztřepené konečky, komplex s mandlovým a arganovým olejem je zjemňuje a dodává jim lesk. Hodí se k domácí péči i do salonu.</p><ul><li>objem 25 ml</li><li>hedvábný protein, keramidy, mandlový a arganový olej</li><li>pro suché, barvené a tepelně namáhané vlasy</li></ul>",
  "GVS-10582": "<p>Lehké nezmývatelné sérum CP-1 s hedvábím a keratinem pro suché a poškozené vlasy. Uzavírá kutikulu, vyhlazuje a zjemňuje, usnadňuje rozčesávání a stylingu a přidává lesk a hedvábný vzhled. Nelepí a chrání vlasy před teplem.</p><ul><li>jednorázová ampule 20 ml</li><li>nezmývatelná péče, lehká textura</li><li>hedvábné proteiny a keratin</li></ul>",
  "GVS-11022": "<p>Lehké nezmývatelné sérum CP-1 s hedvábím a keratinem pro suché a poškozené vlasy. Uzavírá kutikulu, vyhlazuje a zjemňuje, usnadňuje rozčesávání a stylingu a přidává lesk a hedvábný vzhled. Nelepí a chrání vlasy před teplem.</p><ul><li>objem 150 ml</li><li>nezmývatelná péče, lehká textura</li><li>hedvábné proteiny a keratin</li></ul>",
  "GVS-11251": "<p>Proteinová maska CP-1 Premium Hair Treatment pro namáhané vlasy: suché, lámavé, odbarvené i poškozené teplem či chemií. Hedvábný protein a keramidy pomáhají vlasy vyplnit zevnitř a zpevnit roztřepené konečky, komplex s mandlovým a arganovým olejem je zjemňuje a dodává jim lesk. Hodí se k domácí péči i do salonu.</p><ul><li>objem 250 ml</li><li>hedvábný protein, keramidy, mandlový a arganový olej</li><li>pro suché, barvené a tepelně namáhané vlasy</li></ul>",
  "GVS-11848": "<p>Vlasová ampule CP-1 3 Seconds Hair Fill-Up je sérum-maska pro okamžitou obnovu. Uzavírá poškozenou kutikulu, vyplňuje nerovnosti na vlasech a vyhlazuje strukturu, takže vlasy působí hebčeji a pružněji. Obsahuje panthenol, hydrolyzované hedvábí a elastin proti lámavosti.</p><ul><li>objem 170 ml</li><li>regenerační péče pro poškozené vlasy</li><li>panthenol, hydrolyzované hedvábí, elastin</li></ul>",
  "GVS-11978": "<p>Vlasová ampule CP-1 3 Seconds Hair Fill-Up je sérum-maska pro okamžitou obnovu. Uzavírá poškozenou kutikulu, vyplňuje nerovnosti na vlasech a vyhlazuje strukturu, takže vlasy působí hebčeji a pružněji. Obsahuje panthenol, hydrolyzované hedvábí a elastin proti lámavosti.</p><ul><li>jednorázová ampule 13 ml</li><li>regenerační péče pro poškozené vlasy</li><li>panthenol, hydrolyzované hedvábí, elastin</li></ul>",
  "GVS-12005": "<p>Šampon CP-1 s extraktem a olejem ze zázvorového kořene je zaměřený na hloubkové čištění pokožky hlavy. Pomáhá normalizovat činnost mazových žláz a podporuje mikrocirkulaci, vlasy zároveň hydratuje a omezuje jejich lámavost. Díky zázvoru s organickými kyselinami, vitamíny a minerály nechává vlasy čisté a svěží.</p><ul><li>objem 500 ml</li><li>hloubkové čištění pokožky hlavy</li><li>extrakt a olej ze zázvoru</li></ul>",
  "GVS-12012": "<p>Kondicionér CP-1 se zázvorovým kořenem chrání vlasy před poškozením a pomáhá je obnovit. Zázvorový olej a extrakt zvyšují jejich pružnost, vyhlazují kutikulu a zbavují pocitu suchosti a lámavosti. Vlasy jsou hladší a poslušnější, s přirozeným leskem a hedvábným dojmem.</p><ul><li>objem 500 ml</li><li>pro suché a lámavé vlasy</li><li>vyhlazuje kutikulu, dodává lesk</li></ul>",
  "GVS-12074": "<p>Chladivý šampon CP-1 z řady Head Spa s mátou. Důkladně čistí vlasy od nečistot, reguluje tvorbu mazu a zklidňuje pokožku hlavy, takže mírní pocit svědění a odlupování. Máta příjemně chladí a osvěžuje, vlasy zůstávají čisté a zbavené nadměrné mastnoty.</p><ul><li>objem 500 ml</li><li>pro mastnější pokožku hlavy a pocit svěžesti</li><li>řada Head Spa</li></ul>",
  "GVS-12081": "<p>Intenzivně vyživující šampon CP-1 Bright Complex (verze 2.0) s proteiny a kolagenem. Čistí pokožku hlavy a vlasy od nadbytečného mazu a nečistot, ale nevysušuje je. Proteiny vracejí vlasům pružnost a lesk a zmírňují lámavost, jojobový, kaméliový a kokosový olej je chrání. Vhodný pro všechny typy vlasů a denní použití.</p><ul><li>objem 500 ml</li><li>vhodný pro všechny typy vlasů, i pro každodenní mytí</li><li>proteiny, kolagen a rostlinné oleje</li></ul>",
  "GVS-12098": "<p>Kondicionér CP-1 Bright Complex (verze 2.0) funguje hned po opláchnutí i zevnitř. Vyplňuje poškozená místa na vlasech a vyhlazuje keratinové šupiny, takže vlasy jsou zvenčí hladké a uvnitř pevnější. Neobtěžkává je.</p><ul><li>objem 500 ml</li><li>intenzivní výživa a vyhlazení kutikuly</li><li>nezatěžuje vlasy</li></ul>",
  "GVS-12104": "<p>Intenzivně vyživující šampon CP-1 Bright Complex (verze 2.0) s proteiny a kolagenem. Čistí pokožku hlavy a vlasy od nadbytečného mazu a nečistot, ale nevysušuje je. Proteiny vracejí vlasům pružnost a lesk a zmírňují lámavost, jojobový, kaméliový a kokosový olej je chrání. Vhodný pro všechny typy vlasů a denní použití.</p><ul><li>objem 100 ml</li><li>vhodný pro všechny typy vlasů, i pro každodenní mytí</li><li>proteiny, kolagen a rostlinné oleje</li></ul>",
  "GVS-12111": "<p>Kondicionér CP-1 Bright Complex (verze 2.0) funguje hned po opláchnutí i zevnitř. Vyplňuje poškozená místa na vlasech a vyhlazuje keratinové šupiny, takže vlasy jsou zvenčí hladké a uvnitř pevnější. Neobtěžkává je.</p><ul><li>objem 100 ml</li><li>intenzivní výživa a vyhlazení kutikuly</li><li>nezatěžuje vlasy</li></ul>",
  "GVS-12173": "<p>Peelingové sérum Esthetic House Toxheal Red s glykolovou kyselinou, určené k obnově pleti. Odstraňuje odumřelé buňky, vyhlazuje povrch pokožky, čistí a stahuje rozšířené póry a zjasňuje mazové vlásky a černé tečky.</p><ul><li>objem 100 ml</li><li>exfoliace glykolovou kyselinou</li><li>péče o póry a nerovnou texturu pleti</li></ul><p><strong>Použití:</strong> Jde o přípravek s kyselinou: používejte opatrně, nepoužívejte na poškozenou pleť a přes den chraňte pleť krémem s SPF.</p>",
  "GVS-12470": "<p>Peelingové sérum na pokožku hlavy CP-1 Head Spa. Díky AHA a BHA kyselinám a mikrokrystalické celulóze s vitaminy E a C jemně odstraňuje odumřelé buňky, přebytečný maz a nečistoty. Tea tree olej a mátový extrakt pokožku hlavy osvěžují a chladí.</p><ul><li>jednorázová ampule 20 ml</li><li>exfoliace pokožky hlavy</li><li>AHA, BHA, tea tree a máta</li></ul>",
  "GVS-12524": "<p>Šampon CP-1 3 Seconds Hair Fill-Up důkladně čistí pokožku hlavy od nečistot a mazu a zároveň hydratuje. Patentovaný komplex AQUAXYL chrání vlasy před vnějšími vlivy, zlepšuje jejich strukturu a dodává lesk, vlasy jsou poslušné a hedvábné.</p><ul><li>objem 500 ml</li><li>pro poškozené a lámavé vlasy</li><li>patentovaný komplex AQUAXYL</li></ul>",
  "GVS-12531": "<p>Šampon CP-1 3 Seconds Hair Fill-Up důkladně čistí pokožku hlavy od nečistot a mazu a zároveň hydratuje. Patentovaný komplex AQUAXYL chrání vlasy před vnějšími vlivy, zlepšuje jejich strukturu a dodává lesk, vlasy jsou poslušné a hedvábné.</p><ul><li>objem 100 ml</li><li>pro poškozené a lámavé vlasy</li><li>patentovaný komplex AQUAXYL</li></ul>",
  "GVS-13262": "<p>Šampon CP-1 s extraktem a olejem ze zázvorového kořene je zaměřený na hloubkové čištění pokožky hlavy. Pomáhá normalizovat činnost mazových žláz a podporuje mikrocirkulaci, vlasy zároveň hydratuje a omezuje jejich lámavost. Díky zázvoru s organickými kyselinami, vitamíny a minerály nechává vlasy čisté a svěží.</p><ul><li>objem 100 ml</li><li>hloubkové čištění pokožky hlavy</li><li>extrakt a olej ze zázvoru</li></ul>",
  "GVS-13279": "<p>Kondicionér CP-1 se zázvorovým kořenem chrání vlasy před poškozením a pomáhá je obnovit. Zázvorový olej a extrakt zvyšují jejich pružnost, vyhlazují kutikulu a zbavují pocitu suchosti a lámavosti. Vlasy jsou hladší a poslušnější, s přirozeným leskem a hedvábným dojmem.</p><ul><li>objem 100 ml</li><li>pro suché a lámavé vlasy</li><li>vyhlazuje kutikulu, dodává lesk</li></ul>",
  "GVS-13286": "<p>Chladivý šampon CP-1 z řady Head Spa s mátou. Důkladně čistí vlasy od nečistot, reguluje tvorbu mazu a zklidňuje pokožku hlavy, takže mírní pocit svědění a odlupování. Máta příjemně chladí a osvěžuje, vlasy zůstávají čisté a zbavené nadměrné mastnoty.</p><ul><li>objem 100 ml</li><li>pro mastnější pokožku hlavy a pocit svěžesti</li><li>řada Head Spa</li></ul>",
  "GVS-13668": "<p>Šampon CP-1 Aquaxyl Complex Intense Moisture šetrně čistí pokožku hlavy a hydratuje i zjemňuje poškozené vlasy. Patentovaný komplex Aquaxyl™ zajišťuje hydrataci vlasů v několika vrstvách, šampon nevysušuje ani citlivou pokožku hlavy a hodí se pro barvené a odbarvené vlasy. Má pH 5,5 a obsahuje přírodní oleje, aminokyseliny, kolagen, hedvábí a keratin.</p><ul><li>objem 500 ml</li><li>pH 5,5</li><li>vhodný pro barvené a odbarvené vlasy</li></ul>",
  "GVS-13675": "<p>Šampon CP-1 Aquaxyl Complex Intense Moisture šetrně čistí pokožku hlavy a hydratuje i zjemňuje poškozené vlasy. Patentovaný komplex Aquaxyl™ zajišťuje hydrataci vlasů v několika vrstvách, šampon nevysušuje ani citlivou pokožku hlavy a hodí se pro barvené a odbarvené vlasy. Má pH 5,5 a obsahuje přírodní oleje, aminokyseliny, kolagen, hedvábí a keratin.</p><ul><li>objem 100 ml</li><li>pH 5,5</li><li>vhodný pro barvené a odbarvené vlasy</li></ul>",
  "GVS-13699": "<p>Kondicionér CP-1 Aquaxyl Complex Intense Moisture intenzivně hydratuje, obnovuje a zjemňuje poškozené, oslabené a ztracené vlasy, posiluje jejich strukturu a dodává lesk, aniž by je zatěžoval. Díky pH 5,5 poskytuje vyváženou péči a hodí se k obnově po barvení a trvalé.</p><ul><li>objem 500 ml</li><li>pH 5,5</li><li>obnova po barvení a trvalé</li></ul>",
  "GVS-13705": "<p>Kondicionér CP-1 Aquaxyl Complex Intense Moisture intenzivně hydratuje, obnovuje a zjemňuje poškozené, oslabené a ztracené vlasy, posiluje jejich strukturu a dodává lesk, aniž by je zatěžoval. Díky pH 5,5 poskytuje vyváženou péči a hodí se k obnově po barvení a trvalé.</p><ul><li>objem 100 ml</li><li>pH 5,5</li><li>obnova po barvení a trvalé</li></ul>",
  "GVS-13736": "<p>Regenerační kondicionér CP-1 3 Seconds Hair Fill-Up uzavírá poškozenou kutikulu, vyhlazuje povrch vlasů a pomáhá proti roztřepeným konečkům. Vlasy jsou po něm hladší, lesklé a hedvábné, s výrazným antistatickým efektem a ochranou před teplem stylingových nástrojů.</p><ul><li>objem 500 ml</li><li>antistatický efekt</li><li>ochrana před teplem</li></ul>",
  "GVS-13774": "<p>Regenerační kondicionér CP-1 3 Seconds Hair Fill-Up uzavírá poškozenou kutikulu, vyhlazuje povrch vlasů a pomáhá proti roztřepeným konečkům. Vlasy jsou po něm hladší, lesklé a hedvábné, s výrazným antistatickým efektem a ochranou před teplem stylingových nástrojů.</p><ul><li>objem 100 ml</li><li>antistatický efekt</li><li>ochrana před teplem</li></ul>",
  "GVS-13996": "<p>Tonikum Esthetic House Toxheal Red kombinuje tři typy kyselin – AHA, BHA a PHA – pro jemné exfoliační ošetření pleti. Doplňuje exfoliační řadu Toxheal Red s glykolovou kyselinou.</p><ul><li>objem 180 ml</li><li>jemná exfoliace AHA · BHA · PHA</li></ul><p><strong>Použití:</strong> Jde o přípravek s kyselinami: začněte opatrně a přes den používejte krém s SPF.</p>",
  "GVS-14016": "<p>Šampon z řady CP-1 Head Spa s čajovníkem a mátou. Máta dodává vlasům a pokožce hlavy pocit svěžesti, šampon je určený ke každodennímu čištění a osvěžení.</p><ul><li>objem 500 ml</li><li>osvěžující čištění pokožky hlavy</li><li>řada Head Spa</li></ul>",
  "GVS-14375": "<p>Šampon CP-1 Volume Booster dodává vlasům objem u kořínků a šetrně čistí pokožku hlavy. Vlasy jsou hladké a pružné, šampon pomáhá omezit lámavost a zanechává příjemnou vůni s tóny ostružiny, cedru a vetiveru. Odstraňuje nečistoty, maz a odumřelé buňky, aniž by pokožku vysušoval.</p><ul><li>objem 500 ml</li><li>objem u kořínků</li><li>vůně: ostružina, cedr, vetiver</li></ul>",
  "GVS-14382": "<p>Kondicionér CP-1 Volume Booster vyživuje a vyhlazuje vlasy, zabraňuje jejich zacuchání a vrací zdravý lesk. Pomáhá udržet objem u kořínků, takže vlasy zůstávají lehké, pružné a plné pohybu. Zabraňuje suchosti, lámavosti i elektrizování a usnadňuje rozčesávání.</p><ul><li>objem 500 ml</li><li>lehká péče bez zatížení</li><li>antistatický efekt</li></ul>",
  "GVS-14429": "<p>Regenerační maska CP-1 s kolagenem a proteinovým komplexem LPP pro namáhané vlasy. Vyživuje, hydratuje a vyhlazuje, zjemňuje suché a poškozené konečky a předchází lámavosti. Doplňuje nedostatek proteinů a vytváří na vlasech ochrannou vrstvu, při pravidelném používání vlasy obnovuje nejen na povrchu, ale i zevnitř.</p><ul><li>objem 300 ml</li><li>kolagen a proteinový komplex</li><li>pro suché vlasy a poškozené konečky</li></ul>",
  "GVS-14535": "<p>Peelingový přípravek na pokožku hlavy CP-1 Head Spa s růžovou solí. Jemně čistí a masíruje pokožku hlavy a pomáhá odstranit nečistoty a odumřelé částečky.</p><ul><li>objem 200 ml</li><li>růžová sůl pro jemný peeling</li><li>řada Head Spa</li></ul><p><strong>Použití:</strong> Způsob použití najdete na obalu produktu.</p>",
  "GVS-14726": "<p>Šampon z řady CP-1 Detox Purifying Scalp Refresh určený k čištění a osvěžení pokožky hlavy.</p><ul><li>objem 500 ml</li><li>detoxikační čištění pokožky hlavy</li></ul>",
  "GVS-14733": "<p>Šampon z řady CP-1 Detox Purifying Scalp Refresh určený k čištění a osvěžení pokožky hlavy.</p><ul><li>objem 100 ml</li><li>detoxikační čištění pokožky hlavy</li></ul>",
  "GVS-14740": "<p>Kondicionér z řady CP-1 Detox Purifying Scalp Refresh, který doplňuje stejnojmenný šampon a osvěžuje vlasy a pokožku hlavy.</p><ul><li>objem 500 ml</li><li>řada Scalp Refresh</li></ul>",
  "GVS-14757": "<p>Kondicionér z řady CP-1 Detox Purifying Scalp Refresh, který doplňuje stejnojmenný šampon a osvěžuje vlasy a pokožku hlavy.</p><ul><li>objem 100 ml</li><li>řada Scalp Refresh</li></ul>",
  "GVS-14764": "<p>Šampon CP-1 Keratin Intensive Fill-up šetrně čistí pokožku hlavy od přebytečného mazu, odumřelých buněk a zbytků stylingových přípravků a zároveň vlasy hydratuje a zjemňuje. Vlasy jsou po něm hladší, hebčí a lesklejší a poškozené prameny působí upraveněji.</p><ul><li>objem 500 ml</li><li>keratinová péče pro poškozené vlasy</li><li>hladší a lesklejší vlasy</li></ul>",
  "GVS-14771": "<p>Šampon CP-1 Keratin Intensive Fill-up šetrně čistí pokožku hlavy od přebytečného mazu, odumřelých buněk a zbytků stylingových přípravků a zároveň vlasy hydratuje a zjemňuje. Vlasy jsou po něm hladší, hebčí a lesklejší a poškozené prameny působí upraveněji.</p><ul><li>objem 100 ml</li><li>keratinová péče pro poškozené vlasy</li><li>hladší a lesklejší vlasy</li></ul>",
  "GVS-14788": "<p>Regenerační kondicionér CP-1 Keratin Intensive Fill-up s keratinem vrací vlasům hebkost a hedvábný dojem a usnadňuje rozčesávání. Intenzivně hydratuje a pomáhá omezit lámavost a roztřepené konečky.</p><ul><li>objem 500 ml</li><li>keratinová péče pro poškozené vlasy</li><li>snadné rozčesávání</li></ul>",
  "GVS-14795": "<p>Regenerační kondicionér CP-1 Keratin Intensive Fill-up s keratinem vrací vlasům hebkost a hedvábný dojem a usnadňuje rozčesávání. Intenzivně hydratuje a pomáhá omezit lámavost a roztřepené konečky.</p><ul><li>objem 100 ml</li><li>keratinová péče pro poškozené vlasy</li><li>snadné rozčesávání</li></ul>",
  "GVS-1481113": "<p>Oční krém VVBETTER s vitaminem C, bakuchiolem a skvalanem – bělicí a regenerační péče o jemnou pleť kolem očí. Vitamin C pomáhá zesvětlit tmavé kruhy a nerovnoměrný tón, bakuchiol (přírodní alternativa retinolu) cílí na jemné vrásky a pevnost, skvalan drží vlhkost. Vzorek je v praktickém malém balení.</p><ul><li>vzorek 1 ml</li><li>vitamin C, bakuchiol a komplex 8 peptidů</li><li>vegan</li></ul><p><strong>Použití:</strong> Naneste na čistou pleť v okolí očí.</p>",
  "GVS-1482493": "<p>Mírně kyselá čisticí pěna na obličej VVBETTER s pH 5,5, šetrnější k pokožce a vhodná i pro citlivou pleť. Účinně čistí a pomáhá udržet hydrataci, aniž by pleť vysušovala nebo ji napínala.</p><ul><li>vzorek 2 ml</li><li>pH 5,5</li><li>šetrné čištění i pro citlivou pleť</li></ul>",
  "GVS-1482509": "<p>Mírně kyselá čisticí pěna na obličej VVBETTER s pH 5,5, šetrnější k pokožce a vhodná i pro citlivou pleť. Účinně čistí a pomáhá udržet hydrataci, aniž by pleť vysušovala nebo ji napínala.</p><ul><li>objem 120 ml</li><li>pH 5,5</li><li>šetrné čištění i pro citlivou pleť</li></ul>",
  "GVS-14856": "<p>Bezoplachová péče CP-1 Keratin Intensive Fill-up s keratinem, po které jsou vlasy okamžitě hebčí.</p><ul><li>objem 150 ml</li><li>nezmývatelná péče</li><li>keratin pro poškozené vlasy</li></ul>",
  "GVS-1488075": "<p>Čisticí pěna VVBETTER z řady Green Line pro mastnou a problematickou pleť. Extrakt z yuzu, BHA a zinek PCA vytvářejí hustou pěnu, která jemně čistí, odstraňuje nečistoty a přebytečný maz a zachovává hydrataci. Je určená pro pleť náchylnou k akné i pro citlivou pleť.</p><ul><li>objem 145 ml</li><li>extrakt z yuzu, BHA, zinek PCA</li><li>jemné čištění bez podráždění</li></ul>",
  "GVS-251745-DEFECT": "<p><strong>Poškozený obal, produkt neporušený.</strong> Balení této položky je mírně poškozené (promáčknutí/oděrky krabičky), samotný produkt je zcela neporušený a nepoužitý.</p><p>Výživný krém Dr.Althea Rapid Firm Sculpting Cream s extraktem z protěže alpské (edelweiss) z Koreje. Je určený pro unavenou pleť, která potřebuje pevnost a hydrataci: edelweiss funguje jako přírodní antioxidant a pomáhá pleti s elasticitou a vzhledem vrásek. Bohatá textura zanechává pleť vlhkou a mírně zářivou.</p><ul><li>zpevnění a elasticita</li><li>antioxidační a hydratační péče</li><li>bohatá, výživná textura</li></ul>",
  "GVS-251981": "<p>Plátýnková maska Dr.Althea Marine Anti-Blemish s mořskými rostlinnými extrakty a laktobacily, určená k tonizaci, hydrataci a zklidnění pleti. Zmírňuje zarudnutí, pomáhá obnovit lipidovou bariéru, podporuje rovnováhu mikrobiomu a zlepšuje strukturu a pružnost pleti včetně rozšířených pórů.</p><ul><li>plátýnková maska</li><li>zklidňuje a hydratuje</li><li>podporuje mikrobiom a lipidovou bariéru pleti</li></ul>",
  "GVS-253091": "<p>Jemný dokončovací pudr Dr.Althea Face Blur, který opticky vyhlazuje pleť a fixuje make-up.</p><ul><li>opticky vyhlazuje a fixuje líčení</li></ul>",
  "GVS-253473": "<p>Ampulová esence Dr.Althea Skin Relief s 85 % extraktu z pupečníku asijského (centella), pěstovaného v nedotčených oblastech Indie. Vyživuje a zklidňuje citlivou a podrážděnou pokožku, pomáhá s pocitem svědění a zarudnutí a udržuje vlhkost v pleti.</p><ul><li>objem 30 ml</li><li>85 % centella</li><li>pro citlivou a podrážděnou pleť</li></ul>",
  "GVS-253480": "<p>Rozjasňující esence Dr.Althea Natural Radiance s 85 % extraktu z kakadu švestky, která má podle výrobce 150× více vitaminu C než citron. Rozjasňuje matnou pleť, sjednocuje její tón, působí antioxidačně a pomáhá chránit před nežádoucí pigmentací.</p><ul><li>objem 30 ml</li><li>85 % kakadu švestka</li><li>pro mdlou pleť a nerovnoměrný tón</li></ul>",
  "GVS-253756": "<p>Jemný tekutý čisticí prostředek Dr.Althea Premium Quick Step, který odstraňuje přebytečný maz a hloubkově čistí póry, aniž by pokožku fyzicky dráždil. Komplex rostlinných extraktů je vhodný pro všechny typy pleti, kapalná textura se dobře vstřebává a pleť zůstává čistá a svěží.</p><ul><li>čištění pórů a regulace mazu</li><li>vhodný pro všechny typy pleti</li></ul>",
  "GVS-254395": "<p>Oční sérum Dr.Althea To Be Youthful pro jemnou pokožku kolem očí. Hloubkově hydratuje adenosinem, tokoferolem a niacinamidem, posiluje ochrannou bariéru, vyhlazuje jemné linky a podporuje pružnost. Hypoalergenní složení je vhodné pro všechny typy pleti.</p><ul><li>objem 25 ml</li><li>hydratace a pružnost očního okolí</li><li>hypoalergenní složení</li></ul>",
  "GVS-254494": "<p>Veganská dvoufázová sérová mlha Free Moment Green Calming pro okamžité zklidnění pleti. Výživná olejová vrstva z čajového a olivového oleje se spojuje s rostlinnou sérovou fází: 21 rostlinných extraktů, niacinamid a adenosin zklidňují, hydratují a posilují ochrannou bariéru, ideální pro citlivou pleť.</p><ul><li>objem 100 ml</li><li>vegan, dvě vrstvy</li><li>bez parabenů a silikonů</li></ul><p><strong>Použití:</strong> Před použitím protřepejte, aby se vrstvy promísily. Stříkejte z asi 20 cm a jemně vklepejte do pleti.</p>",
  "GVS-254944": "<p>Korejský parfémovaný šampon Free Moment Refresh Moment ve vůni Jeju Camellia. Vůně vydrží celý den, nejen ve sprše: romantická květinová kamélie s oranžovým květem a bergamotem v hlavě, zázvorem a kamélií v srdci a santalem s ambrou v základu. Sirupovitá textura se mění v hustou pěnu, která šetrně čistí pokožku hlavy, mírně kyselé pH podporuje její přirozenou bariéru.</p><ul><li>objem 500 ml</li><li>vůně 01 Jeju Camellia</li><li>vegan, bez parabenů, silikonů a sulfátů</li></ul>",
  "GVS-254951": "<p>Korejský parfémovaný šampon Free Moment Refresh Moment ve vůni Fig Fog. Vůně vydrží celý den a sirupovitá textura se mění v hustou pěnu, která šetrně čistí pokožku hlavy bez vysušení. Mírně kyselé pH podporuje její přirozenou bariéru; složení je bez parabenů, silikonů i sulfátů.</p><ul><li>objem 500 ml</li><li>vůně 02 Fig Fog</li><li>vegan, bez parabenů, silikonů a sulfátů</li></ul>",
  "GVS-254968": "<p>Parfémovaná vlasová péče Free Moment Refresh Moment ve vůni Jeju Camellia. Vyživuje a chrání vlasy, přírodní oleje je zjemňují a dělají hedvábnými a textura typu vodní krém intenzivně hydratuje. Vůně na vlasech vydrží dlouho.</p><ul><li>objem 150 ml</li><li>vůně 01 Jeju Camellia</li><li>oleje a vodní krém pro hebké vlasy</li></ul>",
  "GVS-254975": "<p>Parfémovaná vlasová péče Free Moment Refresh Moment ve vůni Fig Fog. Vyživuje a chrání vlasy, přírodní oleje je zjemňují a dělají hedvábnými a textura typu vodní krém intenzivně hydratuje. Vůně na vlasech vydrží dlouho.</p><ul><li>objem 150 ml</li><li>vůně 02 Fig Fog</li><li>oleje a vodní krém pro hebké vlasy</li></ul>",
  "GVS-255071": "<p>Čisticí balzám Dr.Althea Pure Grinding s pouhými 14 přírodními složkami pro jemné čištění citlivé pleti. Snadno odstraňuje opalovací krém, make-up i voděodolné produkty, olej ze semen kamélie a z hroznových jader s madecassosidem a centellou ho doplňují o hydrataci, takže pleť zůstává měkká.</p><ul><li>14 přírodních složek</li><li>pro citlivou pleť</li><li>odstraňuje i voděodolný make-up</li></ul>",
  "GVS-255101": "<p>Jemné sérum s vitaminem C pro ty, kdo s ním teprve začínají. Rozjasňuje mdlou pleť a pomáhá s tmavými skvrnami. Obsahuje 5 % niacinamidu, 20 % extraktu z plodů rakytníku (Hippophae rhamnoides) a vodu z listů Camellia sinensis. Je vhodné pro citlivou pleť náchylnou k akné, nelepí a nežloutne.</p><ul><li>rozjasnění a tmavé skvrny</li><li>vhodné pro citlivou pleť</li><li>bez lepivého pocitu</li></ul>",
  "GVS-255385-DEFECT": "<p><strong>Poškozený obal, produkt neporušený.</strong> Balení této položky je mírně poškozené (promáčknutí/oděrky krabičky), samotný produkt je zcela neporušený a nepoužitý.</p><p>Jasnicí sérum Dr.Althea pro pleť s pigmentovými skvrnami, stopami po akné a nevyrovnaným tónem. Šedesát tři procent vody z rakytníku (Hippophae Rhamnoides) doplňuje 5 % niacinamidu a 2 % kyseliny tranexamové. Sérum je určené k denní péči, nemá umělé barvivo ani parfemaci a hydratuje, takže je vhodné i pro ty, kterým připadají klasická rozjasňující séra příliš agresivní.</p><ul><li>objem 30 ml, skleněná lahvička s pipetou</li><li>péče o skvrny, matný vzhled a nerovnoměrný tón pleti</li><li>bez umělého barviva a parfemace</li></ul><p>Při pravidelném používání pleť působí jasněji a vyrovnaněji.</p>",
  "GVS-2555218": "<p>Jemná čisticí houbička VVBETTER z konjakového kořene pro šetrné čištění pleti. Je ze 100 % přírodního materiálu a po namočení zjemní.</p><ul><li>1 ks</li><li>přírodní konjakový kořen</li></ul><p><strong>Použití:</strong> Houbičku namočte na několik minut do vody, aby změkla, pak ji s kapkou čisticího přípravku jemně masírujte po pleti asi minutu.</p>",
  "GVS-255620": "<p>Čisticí balzám Dr.Althea Pore Refresh s extraktem ze zeleného čaje a guaiazulenem hloubkově, ale jemně čistí póry a reguluje přebytečný maz. Balení má zabudovaný mechanismus, který balzám promíchá a rozpustí. Rychle rozpouští make-up, uvolňuje ucpané póry a nechává pleť hebkou a hydratovanou. Hodí se pro všechny typy pleti.</p><ul><li>zelený čaj a guaiazulen</li><li>vhodný pro všechny typy pleti</li><li>zabudovaný mlecí mechanismus balení</li></ul>",
  "GVS-255712": "<p>Chladivá plátýnková maska Dr.Althea Cushion Veil zklidňuje podrážděnou pleť a snižuje zarudnutí. Komplex Cica, extrakt z heřmánku a březová voda hloubkově hydratují, posilují kožní bariéru a chrání před vnějšími vlivy. Chladivý efekt je podle výrobce o 30 % vyšší díky studenému kamennému prášku.</p><ul><li>chladivý efekt</li><li>pro citlivou a podrážděnou pleť</li><li>zklidňuje zarudnutí</li></ul>",
  "GVS-255736": "<p>Dvouvrstvá gelová maska Dr.Althea Jelly Seal Dewy obnovuje hydrataci a lipidovou rovnováhu pleti. Obsahuje komplex 10 typů kyseliny hyaluronové, rostlinnou PDRN z listů lotosu a panthenol s madecassosidem. Je vhodná pro citlivou a smíšenou pleť a dává jí vláčný, svěží vzhled.</p><ul><li>10 typů kyseliny hyaluronové</li><li>rostlinná PDRN z lotosu</li><li>pro citlivou a smíšenou pleť</li></ul>",
  "GVS-255750": "<p>Ultra hydratační plátýnková maska Dr.Althea Aqua Blue pro hloubkovou hydrataci a zklidnění citlivé pleti. Podle výrobce poskytuje 24hodinovou hydrataci, obsahuje azulen a extrakt ze spiruliny, pomáhá zmírnit otoky a zarudnutí a posiluje přirozenou bariéru pleti.</p><ul><li>24hodinová hydratace podle výrobce</li><li>azulen a extrakt ze spiruliny</li><li>pro citlivou pleť</li></ul>",
  "GVS-255811": "<p>Botanická plátýnková maska Dr.Althea Vita Glow ze 100% lyocellu pro svěží a zářivý vzhled pleti. Sérum s botanickými extrakty bohatými na vitamin C a niacinamid hydratuje, podporuje zářivost a pomáhá s hyperpigmentací.</p><ul><li>maska ze 100 % lyocellu</li><li>vitamin C a niacinamid</li><li>rozjasnění a hydratace</li></ul>",
  "GVS-2559544": "<p>Krém na obličej VVBETTER s patentovanou složkou TECA, 9 peptidy a vitaminem C, který pomáhá zpevnit a rozjasnit tón pleti a obnovit poškozenou pokožku. Obsahuje 53 % extraktu z centelly asijské z Madagaskaru. Vzorek je malé balení pro vyzkoušení.</p><ul><li>vzorek 2 ml</li><li>komplex TECA, 9 peptidů, vitamin C</li><li>53 % centella asijská</li></ul>",
  "GVS-255972": "<p>Hydratační opalovací krém Dr.Althea Aqua Glowing SPF50+ PA++++ s lehkou vodnatou texturou a vlhkým „aqua glow“ finišem. Chrání před UVA i UVB zářením a zároveň hydratuje, nelepí a nemastí. Obsahuje panthenol a extrakt z mořské řasy Caulerpa lentillifera, hodí se pro suchou a nevyváženou pleť.</p><ul><li>SPF50+ PA++++</li><li>objem 45 ml</li><li>bez lepivého a mastného pocitu</li></ul>",
  "GVS-256115": "<p>Dvouvrstvá hydratační mlha Dr.Althea 345 Relief Cream Mist spojuje osvěžující vodní vrstvu s lehkou krémovou vrstvou. Obsahuje 60 % vody z rýžových otrub a 10 000 ppm panthenolu, má hedvábnou texturu a hodí se pro pleť, která je napjatá nebo dehydrovaná během dne, i před make-upem.</p><ul><li>objem 100 ml</li><li>dvě vrstvy: voda a krém</li><li>60 % voda z rýžových otrub, 10 000 ppm panthenol</li></ul>",
  "GVS-256115-DEFECT": "<p><strong>Poškozený obal, produkt neporušený.</strong> Balení této položky je mírně poškozené (promáčknutí/oděrky krabičky), samotný produkt je zcela neporušený a nepoužitý.</p><p>Dvouvrstvá hydratační mlha Dr.Althea 345 Relief Cream Mist spojuje osvěžující vodní vrstvu s lehkou krémovou vrstvou. Obsahuje 60 % vody z rýžových otrub a 10 000 ppm panthenolu, má hedvábnou texturu a hodí se pro pleť, která je napjatá nebo dehydrovaná během dne, i před make-upem.</p><ul><li>objem 100 ml</li><li>dvě vrstvy: voda a krém</li><li>60 % voda z rýžových otrub, 10 000 ppm panthenol</li></ul>",
  "GVS-256122": "<p>Dvouvrstvá hydratační mlha Dr.Althea 345 Relief Cream Mist spojuje osvěžující vodní vrstvu s lehkou krémovou vrstvou. Obsahuje 60 % vody z rýžových otrub a 10 000 ppm panthenolu, má hedvábnou texturu a hodí se pro pleť, která je napjatá nebo dehydrovaná během dne, i před make-upem.</p><ul><li>objem 60 ml</li><li>dvě vrstvy: voda a krém</li><li>60 % voda z rýžových otrub, 10 000 ppm panthenol</li></ul>",
  "GVS-256122-DEFECT": "<p><strong>Poškozený obal, produkt neporušený.</strong> Balení této položky je mírně poškozené (promáčknutí/oděrky krabičky), samotný produkt je zcela neporušený a nepoužitý.</p><p>Dvouvrstvá hydratační mlha Dr.Althea 345 Relief Cream Mist spojuje osvěžující vodní vrstvu s lehkou krémovou vrstvou. Obsahuje 60 % vody z rýžových otrub a 10 000 ppm panthenolu, má hedvábnou texturu a hodí se pro pleť, která je napjatá nebo dehydrovaná během dne, i před make-upem.</p><ul><li>objem 60 ml</li><li>dvě vrstvy: voda a krém</li><li>60 % voda z rýžových otrub, 10 000 ppm panthenol</li></ul>",
  "GVS-256184": "<p>Veganská hydratační mlha Dr.Althea Aqua Marine Jelly Mist s 10 % mořské vody z hlubin u korejského ostrova Ulleungdo a veganskou PDRN. Ultrajemná mlha pleť hydratuje a dává jí svěží „želé“ lesk, je šetrná k citlivé pleti a přírodně modrá díky extraktu z malachitu.</p><ul><li>10 % hlubinná mořská voda, vegan PDRN</li><li>jemná mlha, šetrná k citlivé pleti</li><li>hydratace a „jelly“ lesk</li></ul>",
  "GVS-256221-DEFECT": "<p><strong>Poškozený obal, produkt neporušený.</strong> Balení této položky je mírně poškozené (promáčknutí/oděrky krabičky), samotný produkt je zcela neporušený a nepoužitý.</p><p>Lehký denní krém Dr.Althea 345 Relief Cream pro aknózní, citlivou a smíšenou pleť s následky po akné – zarudnutím, nerovnou strukturou nebo skvrnami. Niacinamid rozjasňuje, ceramid NP dlouhodobě hydratuje a pomáhá obnovit narušenou ochrannou bariéru, aniž by pleť zatížil. Krém je testován na citlivé pleti a nekomedogenní.</p><ul><li>objem 50 ml</li><li>zklidnění a hydratace pleti po akné</li><li>lehká, nemastná textura</li></ul>",
  "GVS-256238": "<p>Pěnové sérum Dr.Althea ABC Glow Whipped spojuje tonikum, sérum a bublinkovou masku v jednom kroku. Vzduchové bublinky se rychle vstřebávají a zanechávají lehký, nelepivý, zářivý povrch. Jedna dávka funguje jako tonikum, tři dávky jako hydratační bublinková maska.</p><ul><li>3 v 1: tonikum, sérum a maska</li><li>pěna, která se mění ve vodu</li><li>rychle se vstřebává</li></ul>",
  "GVS-256276": "<p>Báze pod make-up Dear.A Cool Fit Primer sjednocuje texturu pleti a připravuje ji na dlouhodobé líčení.</p><ul><li>báze pod make-up</li></ul>",
  "GVS-256283": "<p>Zklidňující plátýnková maska Dr.Althea 345 Relief Cream pomáhá hydratovat, zjemnit a obnovit poškozenou pleť. Zmírňuje zarudnutí a podráždění, podporuje přirozenou regeneraci pleti a posiluje její bariéru. Navazuje na krém 345 Relief Cream ze stejné řady.</p><ul><li>plátýnková maska, 25 g</li><li>zklidnění a obnova pleti</li><li>řada 345 Relief</li></ul>",
  "GVS-256306": "<p>Zklidňující polštářky Dr.Althea StretchFit se dají libovolně natáhnout, takže přiléhají na jakoukoli oblast obličeje. 15 cm dlouhé pásky s chladivým erythritolem zklidňují citlivou a rozpálenou pleť, 1 % panthenolu dlouhodobě hydratuje a podporuje bariéru pleti.</p><ul><li>balení 50 ks</li><li>délka 15 cm, přizpůsobí se tvaru obličeje</li><li>erythritol a 1 % panthenolu</li></ul>",
  "GVS-256429": "<p>Regenerační krém Dr.Althea 345 Relief Cream s texturou gel-krém-mast. Niacinamid, panthenol a extrakt z opuncie pomáhají s následky akné a zároveň vyživují a hydratují, aniž by pleť zatěžovaly. Je určen pro aknózní, citlivou a smíšenou pleť.</p><ul><li>objem 15 ml</li><li>niacinamid, panthenol, opuncie</li><li>pro pleť s následky po akné</li></ul>",
  "GVS-256429-DEFECT": "<p><strong>Poškozený obal, produkt neporušený.</strong> Balení této položky je mírně poškozené (promáčknutí/oděrky krabičky), samotný produkt je zcela neporušený a nepoužitý.</p><p>Regenerační krém Dr.Althea 345 Relief Cream s texturou gel-krém-mast. Niacinamid, panthenol a extrakt z opuncie pomáhají s následky akné a zároveň vyživují a hydratují, aniž by pleť zatěžovaly. Je určen pro aknózní, citlivou a smíšenou pleť.</p><ul><li>objem 15 ml</li><li>niacinamid, panthenol, opuncie</li><li>pro pleť s následky po akné</li></ul>",
  "GVS-256795": "<p>Hluboce hydratační krém Dr.Althea 147 Barrier pro suchou, dehydrovanou a citlivou pleť s narušenou bariérou. Patentovaný extrakt z květů pivoňky (Paeonia Albiflora), extrakt z avokáda a arganový olej vyživují a posilují kožní bariéru, sedmivrstvé složení s kyselinou hyaluronovou podporuje pevnost pleti. Bohatá, ale příjemná textura se hodí zvlášť na noc.</p><ul><li>objem 50 ml</li><li>posiluje kožní bariéru</li><li>pro suchou a citlivou pleť</li></ul>",
  "GVS-256795-DEFECT": "<p><strong>Poškozený obal, produkt neporušený.</strong> Balení této položky je mírně poškozené (promáčknutí/oděrky krabičky), samotný produkt je zcela neporušený a nepoužitý.</p><p>Hluboce hydratační krém Dr.Althea 147 Barrier pro suchou, dehydrovanou a citlivou pleť s narušenou bariérou. Patentovaný extrakt z květů pivoňky (Paeonia Albiflora), extrakt z avokáda a arganový olej vyživují a posilují kožní bariéru, sedmivrstvé složení s kyselinou hyaluronovou podporuje pevnost pleti. Bohatá, ale příjemná textura se hodí zvlášť na noc.</p><ul><li>objem 50 ml</li><li>posiluje kožní bariéru</li><li>pro suchou a citlivou pleť</li></ul>",
  "GVS-3005205-DEFECT": "<p><strong>Poškozený obal, produkt neporušený.</strong> Balení této položky je mírně poškozené (promáčknutí/oděrky krabičky), samotný produkt je zcela neporušený a nepoužitý.</p><p>Zklidňující hydratační krém Polatam pro citlivou pleť. Kyselina hyaluronová v několika formách, extrakt z centelly asijské a extrakt z malachitu zajišťují vlhkost a komfort, ceramid NP, sheabutter a skvalan pleť vyživují. Pleť působí svěže a zářivě.</p><ul><li>objem 50 ml</li><li>určený pro citlivou pleť</li><li>řada Cica Malacalming</li></ul><p><strong>Použití:</strong> malé množství naneste na čistou pleť podle potřeby.</p>",
  "GVS-3012017": "<p>Exfoliační tonikum VVBETTER s AHA kyselinami (glykolová a mléčná) jemně odstraňuje odumřelé buňky a nečistoty a dodává pleti zdravý lesk. Neutrální pH 5,5 pomáhá nedráždit ani citlivou pleť, kyselina hyaluronová, betain a glycerin pleť hydratují a centella ji zklidňuje. Hodí se pro všechny typy pleti.</p><ul><li>objem 200 ml</li><li>jemná exfoliace s pH 5,5</li><li>vhodné pro všechny typy pleti</li></ul>",
  "GVS-3013175": "<p>Lehké zpevňující sérum VVBETTER s 10 000 ppm bakuchiolu – rostlinné alternativy retinolu – a veganskou PDRN. Pomáhá zlepšit pružnost, vyhladit jemné vrásky a jemně hydratuje díky 60% vodě z listů aloe vera.</p><ul><li>objem 30 ml</li><li>bakuchiol 10 000 ppm a vegan PDRN</li><li>60 % voda z aloe vera</li></ul>",
  "GVS-3013182": "<p>Lehké rozjasňující sérum VVBETTER proti pigmentovým skvrnám a nerovnoměrnému tónu pleti. Obsahuje 72 % rakytníkové vody a 3 % kyseliny tranexamové, niacinamid a adenosin pomáhají tón sjednotit a pleť rozjasnit.</p><ul><li>objem 30 ml</li><li>72 % rakytníková voda, 3 % tranexamová kyselina</li><li>rozjasnění a sjednocení tónu pleti</li></ul>",
  "GVS-541881": "<p>Koncentrovaná keratinová esence CP-1 pro suché, lámavé a krepovité vlasy. Pomáhá udržet správnou hladinu vlhkosti, vrací vlasům pružnost a lesk, opravuje poškozená místa a předchází roztřepeným konečkům. Lehká textura připomíná odtučněný olej, takže vlasy nezatěžuje. Obsahuje keratin, extrakt z listů baobabu a elastin a je bez sulfátů.</p><ul><li>objem 10 ml</li><li>esence pro suché, lámavé a krepovité vlasy</li><li>bez sulfátů</li></ul>",
  "GVS-5903568": "<p>Denní opalovací krém VVBETTER Airfit s SPF50+ PA++++ a lehkou hydratační konzistencí. Technologie AirFit zajišťuje rychlé vstřebání bez bílých stop i lepkavosti, skvalan, panthenol a madecassosid pleť zároveň regenerují. Je hypoalergenní, nekomedogenní a vegan certifikovaný.</p><ul><li>SPF50+ PA++++, chrání před UVA i UVB</li><li>bez bílých stop</li></ul>",
  "GVS-5904008": "<p>Denní opalovací krém VVBETTER Airfit s SPF50+ PA++++ a lehkou hydratační konzistencí. Technologie AirFit zajišťuje rychlé vstřebání bez bílých stop i lepkavosti, skvalan, panthenol a madecassosid pleť zároveň regenerují. Je hypoalergenní, nekomedogenní a vegan certifikovaný. Tato položka je malý vzorek.</p><ul><li>vzorek 1 ml</li><li>SPF50+ PA++++, chrání před UVA i UVB</li><li>bez bílých stop</li></ul>",
  "GVS-5904305": "<p>Jemný čisticí olej VVBETTER s více než 80 % přírodních rostlinných olejů pro hloubkové čištění pleti, odstranění make-upu, opalovacího krému, nečistot a mazu. Pelyněk, centella asijská a niacinamid zklidňují citlivou pleť, skvalan a panthenol ji vyživují a regenerují.</p><ul><li>objem 200 ml</li><li>80 % rostlinných olejů</li><li>pelyněk, centella, niacinamid</li></ul>",
  "GVS-6550430": "<p>Cestovní sada VVBETTER Travel Kit Blue s hydratační a exfoliační rutinou o čtyřech krocích: čisticí pěna 5.5 Soothing Cleansing Foam (20 ml), tonikum AHA Boosting Toner (30 ml), sérum TECA Lifting Moisture Serum (10 ml) a krém Lifting Moisture Cream (10 ml). Hodí se na cesty, do posilovny i jako dárek nebo jako vyzkoušení oblíbených produktů značky bez nutnosti kupovat velká balení.</p><ul><li>4 miniaturní produkty</li><li>cestovní velikost</li><li>kosmetika testovaná na podráždění</li></ul>",
  "GVS-6555893": "<p>Lehké vyvažující sérum VVBETTER z řady Green Line pro pleť náchylnou k nedokonalostem a lesku. Obsahuje 60 % bambusové vody pro zklidnění a 40 000 ppm kyseliny jantarové s niacinamidem, které pomáhají zmírnit zarudnutí a zlepšit texturu pleti.</p><ul><li>objem 30 ml</li><li>60 % bambusová voda, kyselina jantarová, niacinamid</li><li>pro pleť s lesklými a problematickými místy</li></ul><p><strong>Použití:</strong> Doporučené pořadí v rutině podle výrobce: zklidňující sérum, sérum s vitaminem C, sérum s bakuchiolem, opalovací krém.</p>",
  "GVS-7119180": "<p>Vyvažující gelový krém VVBETTER z řady Green Line s extraktem z yuzu, zinkem PCA a ceramidovými mikrokapslemi pro dlouhodobou hydrataci a obnovu bariéry pleti. Patentovaný komplex MOISTURE B (0,5 %) rychle zklidňuje citlivou pleť, zklidňující extrakty z centelly a houttuynie ji podporují.</p><ul><li>objem 50 ml</li><li>ceramidové mikrokapsle</li><li>yuzu, zinek PCA, centella</li></ul>",
  "GVS-7119623": "<p>Tonikové polštářky VVBETTER z řady Green Line s extraktem z yuzu, zinkem PCA a PHA pro každodenní tonizaci. Vyvinuté pro zklidnění citlivé pleti a péči o hladkou a hydratovanou texturu. Toto balení je v pouzdru (pouch).</p><ul><li>extrakt z yuzu, zinek PCA, PHA</li><li>pro citlivou pleť</li><li>balení v pouzdru</li></ul>",
  "GVS-7251943": "<p>Zklidňující plátýnková maska Dr.Althea Oasis hloubkově proniká do suché a citlivé pokožky. Podle výrobce poskytuje „460× intenzivnější“ hydrataci. Obsahuje extrakt z Anastatica Hierochuntica („růže z Jericha“) a komplex šesti základních složek péče o pleť.</p><ul><li>plátýnková maska</li><li>pro suchou a citlivou pleť</li><li>extrakt z růže z Jericha</li></ul>",
  "GVS-9177655": "<p>Jemná čisticí maska z jílu VVBETTER bohatá na minerály. Bentonit a kaolin účinně absorbují nečistoty a maz, pomáhají snížit viditelnost černých teček a pórů a zlepšují strukturu pleti. Obsahuje centellu asijskou, niacinamid, skvalan, panthenol, bakuchiol a 8 peptidů.</p><ul><li>objem 60 ml</li><li>bentonit a kaolin</li><li>centella, niacinamid, skvalan, 8 peptidů</li></ul>",
};

async function main() {
  let updated = 0;
  for (const [code, description] of Object.entries(TEXTS)) {
    const product = await prisma.product.findUnique({ where: { code }, select: { id: true, name: true, description: true } });
    if (!product) {
      console.log(`  [skip] not found: ${code}`);
      continue;
    }
    console.log(`  ${code} ${product.name.slice(0, 48)}: ${(product.description ?? "").length} -> ${description.length} chars`);
    if (DRY_RUN) continue;
    await prisma.product.update({ where: { id: product.id }, data: { description } });
    updated++;
  }
  if (!DRY_RUN && updated > 0) {
    await logAdminActivity({ action: "product.gvs_descriptions", entityType: "Product", detail: `GVS: Czech descriptions written for the remaining ${updated} products` });
  }
  console.log(`\nDone. ${updated} updated.`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
