// Czech descriptions (and INCI where a source lists it) for the 20 most relevant
// GVS Cosmetics products: the 7 that have sold plus 13 of the highest-priced.
// Written 2026-10-09 in our own words from the brands' own product pages
// (doctoraltheaglobal.com, vvbetter.com), K-beauty retailers (kosmosbeauty.com,
// cosmeterie.com, saranghae.ch, theskincarelibrary.com) — facts only, no medical
// claims, nothing invented about usage that no source states. INCI is only set
// for the four Polatam items whose full list cosmeterie publishes; the DEFECT
// (damaged-packaging) siblings keep their own text.
//
// Usage: npx tsx scripts/set-gvs-descriptions.ts --dry-run | (no flag = apply)
import { prisma } from "../src/lib/prisma";
import { logAdminActivity } from "../src/lib/admin/activity-log";

const DRY_RUN = process.argv.includes("--dry-run");

const TEXTS: Record<string, { description: string; ingredients?: string }> = {
  "GVS-3006318": { description: "<p>Hydratační krém z korejské řady Cica Malacalming (značka Polatam) pro suchou pleť. Základem je extrakt z centelly asijské doplněný o extrakt z malachitu, pupalky a borovice, a také allantoin, panthenol a kyselinu hyaluronovou. Díky nim se pleť po nanesení cítí vyživená a pružná.</p><ul><li>objem 50 ml</li><li>vhodný pro suchou pleť</li><li>obsahuje ceramid NP, sheabutter a skvalan</li></ul><p><strong>Použití:</strong> malé množství naneste na čistou pleť podle potřeby.</p>", ingredients: "Aqua, Glycerin, Caprylic/Capric Triglyceride, 1.2-Hexanediol, Butylene Glycol, Centella Asiatica Extract, Polyglyceryl-2 Stearate, Malachite Extract, Panthenol, Squalen, Glyceryl Glucoside, Butyrospermum Parkii (Shea) Butter, Allantoin, Ceramide Np, Cholesterol, Olea Europaea (Olive) Oil, Sodium Hyaluronate, Arginin, Phytosphingosine, Saccharomyces/Rice Ferment Filtrate, Cera Alba (Beeswax), Adenosine, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Oenothera Biennis (Evening Primrose) Flower Extract, Pueraria Lobata Root Extract, Pentylene Glycol, Hydrogenated Lecithin, Glyceryl Stearate, Hydrogenated Polydecene, Caprylyl Methicone, Coco Caprylate/Caprate, Carbomer, Stearyl Alcohol, Ethylhexylglycerin, Xanthan Gum, Cetyl Alcohol, Polyglyceryl-3 Methylglucose Distearate" },
  "GVS-3255167": { description: "<p>Textilní maska od značky VVBETTER se skvalenem, kolagenem a veganskou PDRN, určená pro unavenou pleť, která potřebuje vypadat svěžeji a pevněji. Maska je dermatologicky testovaná a vhodná i pro citlivou pleť, přilne k obličeji díky střihu Comfort Fit a receptura je veganská a bez agresivních složek.</p><ul><li>balení: 5 masek po 28 ml</li><li>zpevňující a vyhlazující péče o unavenou pleť</li><li>vegan certifikovaná receptura</li></ul><p><strong>Použití:</strong> po očištění a toniku maskou rozložte, odstraňte fólii a přiložte na obličej na 10–20 minut. Zbylou esenci jemně vklepejte do pleti.</p>" },
  "GVS-2554853": { description: "<p>Lehký denní krém z řady Teca Lifting od VVBETTER pro pleť, která potřebuje hydrataci i pevnost. Kyselina hyaluronová dodává vlhkost, extrakt z centelly asijské (v krému jí je 53 %) pleť zklidňuje a komplex TECA – kyselina asiatová, asiatikosid a madekasová kyselina – podporuje její regeneraci.</p><ul><li>objem 50 ml</li><li>9 peptidů, adenosin a niacinamid pro pevnější a vyrovnanější pleť</li><li>vhodný i pro citlivou pleť, lehká textura</li></ul><p>Krém dobře funguje jako samostatná denní péče nebo jako poslední krok rutiny po séru Teca Lifting Moisture Serum.</p>" },
  "GVS-255385": { description: "<p>Jasnicí sérum Dr.Althea pro pleť s pigmentovými skvrnami, stopami po akné a nevyrovnaným tónem. Šedesát tři procent vody z rakytníku (Hippophae Rhamnoides) doplňuje 5 % niacinamidu a 2 % kyseliny tranexamové. Sérum je určené k denní péči, nemá umělé barvivo ani parfemaci a hydratuje, takže je vhodné i pro ty, kterým připadají klasická rozjasňující séra příliš agresivní.</p><ul><li>objem 30 ml, skleněná lahvička s pipetou</li><li>péče o skvrny, matný vzhled a nerovnoměrný tón pleti</li><li>bez umělého barviva a parfemace</li></ul><p>Při pravidelném používání pleť působí jasněji a vyrovnaněji.</p>" },
  "GVS-256191": { description: "<p>Lehké veganské pleťové sérum pro všechny typy pleti, které se rychle vstřebává a nelepí. Základem je 70 % vody z bambusu (Bambusa Vulgaris) a patentovaná technologie 3D kyseliny hyaluronové, která dlouhodobě hydratuje a podporuje bariéru pleti. Po nanesení zůstává svěží, jemně zářivý vzhled.</p><ul><li>objem 30 ml</li><li>vhodné pro všechny typy pleti, včetně mastné a smíšené</li><li>nemastné, rychle se vstřebává, pleť zůstává svěže vlhká</li></ul><p>Sérum používejte po čištění a toniku, před krémem.</p>" },
  "GVS-255033": { description: "<p>Lokální péče Dr.Althea na problematická místa. Dvouvrstvá formule spojuje zklidňující esenci s práškovou vrstvou obsahující 15 % vysoce čistého kalaminu. Kalamin a extrakt ze zeleného čaje pomáhají zklidnit podrážděná místa, kyselina salicylová zjemňuje strukturu pleti a reguluje přebytečný maz a liposomální ceramid podporuje hydrataci a ochrannou bariéru.</p><ul><li>objem 15 ml, aplikátor s měkkou špičkou</li><li>cílená péče o jednotlivá místa, nenanášejte na celý obličej</li><li>nepoužívat na poškozenou pokožku</li></ul><p><strong>Použití:</strong> lahvičku před použitím netřepejte, kapku naneste přímo na místo a nechte působit přes noc. Ráno opláchněte.</p>" },
  "GVS-10933": { description: "<p>Peelingový přípravek na pokožku hlavy z řady Head Spa značky CP-1 (Esthetic House). Důkladně, ale šetrně čistí od nečistot a odlupuje odumřelé částečky pokožky. Obsahuje mořskou sůl, kyselinu glykolovou a jemné tenzidy rostlinného původu a také mentol a extrakt z máty peprné, které příjemně chladí a dávají pocit svěžesti a čistoty.</p><ul><li>objem 210 ml</li><li>hloubkové čištění a jemný peeling pokožky hlavy</li><li>chladivý pocit díky mentolu</li></ul><p>Způsob použití najdete na obalu produktu.</p>" },
  "GVS-3005205": { description: "<p>Zklidňující hydratační krém Polatam pro citlivou pleť. Kyselina hyaluronová v několika formách, extrakt z centelly asijské a extrakt z malachitu zajišťují vlhkost a komfort, ceramid NP, sheabutter a skvalan pleť vyživují. Pleť působí svěže a zářivě.</p><ul><li>objem 50 ml</li><li>určený pro citlivou pleť</li><li>řada Cica Malacalming</li></ul><p><strong>Použití:</strong> malé množství naneste na čistou pleť podle potřeby.</p>", ingredients: "Aqua, Butylene Glycol, 1.2-Hexanediol, Triethylcitrate, Centella Asiatica Extract, Propandiol, Pentylene Glycol, Diethoxyethyl Succinate, Malachite Extract, Squalen, Hyaluronic Acid, Hydrolyzed Hyaluronic Acid, Hydrolyzed Sodium Hyaluronate, Sodium Hyaluronate Crosspolymer, Sodium Acetylated Hyaluronate, Sodium Hyaluronate, Ceramide Np, Butyrospermum Parkii (Shea) Butter, Olea Europaea (Olive) Oil, Phytosphingosine, Cholesterol, Arginin, Castanea Crenata (Chestnut) Shell Extract, Brassica Oleracea Italica (Broccoli) Extract, Medicago Sativa (Alfalfa) Extract, Brassica Oleracea Capitata (Cabbage) Leaf Extract, Triticum Vulgare Germ Extract, Artemisia Capillaris Extract, Brassica Campestris (Rapeseed) Extract, Raphanus Sativus (Radish) Root Extract, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Oenothera Biennis (Evening Primrose) Flower Extract, Pueraria Lobata Root Extract, Caprylyl Glycol, Olea Europaea (Olive) Fruit Extract, C12-13 Alketh-9, Acrylates C10-30 Alkyl Acrylate Crosspolymer, Polyglyceryl -10 Laurate, Ammonium Acryloyldimethyltaurate/Vp Copolymer, Glycerin, Caprylic/Capric Triglyceride, Hydrogenated Lecithin" },
  "GVS-2559933": { description: "<p>Oční krém od VVBETTER, který kombinuje vitamin C, bakuchiol a skvalan. Vitamin C pomáhá zesvětlit tmavé kruhy a nerovnoměrný tón, bakuchiol (přírodní alternativa retinolu) cílí na jemné vrásky a pevnost a skvalan drží vlhkost v pleti. Krém se dávkuje otočnou pumpičkou – stačí otočit, stlačit a nanést.</p><ul><li>objem 30 ml</li><li>péče o oční okolí: tmavé kruhy, jemné vrásky, pevnost</li><li>šetrná alternativa k retinolu</li></ul><p>Naneste na čistou pleť v okolí očí.</p>" },
  "GVS-7118671": { description: "<p>Tonikové polštářky Jeju Yuja Balancing Pad od VVBETTER s vysokým obsahem extraktu z korejského citrusu yuja, který je zdrojem vitamínu C. Jemná PHA (glukonolakton) odstraňuje odumřelé buňky bez podráždění, komplex MOISTURE B hydratuje a zinek PCA pomáhá regulovat přebytečný maz. Výrobek má certifikaci korejského veganského institutu.</p><ul><li>balení 120 polštářků, 180 ml</li><li>jemná exfoliace a hydratace v jednom kroku</li><li>vegan certifikace, bez testování na zvířatech</li></ul><p>Polštářky používejte po očištění pleti, před sérem a krémem.</p>" },
  "GVS-2554846": { description: "<p>Pleťové sérum z řady Teca Lifting (VVBETTER) pro pleť, která potřebuje hydrataci, pevnost a svěží vzhled. Centella asijská a kyselina hyaluronová pomáhají udržet vlhkost a zklidnit pleť, adenosin a niacinamid vyrovnávají tón a osm peptidů podporuje její pevnost. Chytrá pipeta je už v lahvičce hotová k použití, takže dávkování je snadné.</p><ul><li>objem 30 ml</li><li>hydratace, zklidnění a pevnost pleti</li><li>chytrá pipeta pro přesné dávkování</li></ul><p>Sérum používejte po čištění a toniku, před krémem. Dobře se doplňuje s krémem ze stejné řady Teca Lifting.</p>" },
  "GVS-3005922": { description: "<p>Hydratační pleťové polštářky Polatam namočené v koncentrované esenci. Díky tomu připomínají ampulovou péči: obsahují extrakty z centelly asijské, malachitu, borovice, pupalky, papáji, vinné révy a brokolice a také kyselinu hyaluronovou v několika formách. Jsou určené pro citlivou pleť, která si zaslouží něco navíc.</p><ul><li>balení 100 ks</li><li>přiložení polštářku na vybranou část pleti</li><li>zklidňující a hydratační péče pro citlivou pleť</li></ul><p><strong>Použití:</strong> na suchou a čistou pleť přiložte polštářek na požadované místo a nechte několik minut působit.</p>", ingredients: "Aqua, 1.2-Hexanediol, Centella Asiatica Extract, Glycerin, Butylene Glycol, Malachite Extract, Hyaluronic Acid, Hydrolyzed Hyaluronic Acid, Hydrolyzed Sodium Hyaluronate, Sodium Hyaluronate Crosspolymer, Sodium Acetylated Hyaluronate, Sodium Hyaluronate, Madecassoside, Madecassic Acid, Asiaticoside, Asiatic Acid, Melia Azadirachta Leaf Extract, Melia Azadirachta Flower Extract, Houttuynia Cordata Extract, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Oenothera Biennis (Evening Primrose) Flower Extract, Pueraria Lobata Root Extract, Carica Papaya (Papaya) Fruit Extract, Malus Domestica Fruit Extract, Prunus Mume Fruit Extract, Vitis Vinifera Fruit Extract, Brassica Oleracea Italica (Broccoli) Extract, Medicago Sativa (Alfalfa) Extract, Brassica Oleracea Capitata (Cabbage) Leaf Extract, Triticum Vulgare Germ Extract, Brassica Campestris (Rapeseed) Extract, Raphanus Sativus (Radish) Root Extract, Saccharomyces Ferment, Cryptomeria Japonica Leaf Extract, Nelumbo Nucifera Leaf Extract, Hydroxyacetophenone, Disodium Edta" },
  "GVS-251745": { description: "<p>Výživný krém Dr.Althea Rapid Firm Sculpting Cream s extraktem z protěže alpské (edelweiss) z Koreje. Je určený pro unavenou pleť, která potřebuje pevnost a hydrataci: edelweiss funguje jako přírodní antioxidant a pomáhá pleti s elasticitou a vzhledem vrásek. Bohatá textura zanechává pleť vlhkou a mírně zářivou.</p><ul><li>zpevnění a elasticita</li><li>antioxidační a hydratační péče</li><li>bohatá, výživná textura</li></ul>" },
  "GVS-256412": { description: "<p>Krém Dr.Althea PDRN Reju 5000 s 5 000 ppm veganské PDRN (z pěti fermentovaných složek) a 50 000 ppm vody z listů centelly asijské. Pomáhá zklidnit podrážděnou pleť, posilovat její bariéru a pružnost. Maznavá, ale nemastná textura se dobře vstřebává a dá se vrstvit podle typu pleti.</p><ul><li>PDRN 5 000 ppm, centella</li><li>zklidnění a pevnost pleti, denní péče nebo „SOS“ ošetření</li><li>veganská formule</li></ul>" },
  "GVS-3005106": { description: "<p>Intenzivní pleťové sérum Polatam pro citlivou pleť. Obsahuje extrakt z centelly asijské, malachitu a rostlinné extrakty (brokolice, pupalka, borovice, bambus, zimolez, oliva) spolu s panthenolem a glycerinem. Pleť zůstává vyživená a příjemně hydratovaná.</p><ul><li>objem 50 ml</li><li>určeno pro citlivou pleť</li><li>řada Cica Malacalming</li></ul><p><strong>Použití:</strong> malé množství séra jemně vklepejte do čisté pleti.</p>", ingredients: "Aqua, Butylene Glycol, 1.2-Hexanediol, Centella Asiatica Extract, Glycerin, Malachite Extract, Panthenol, Sodium Hyaluronate, Brassica Oleracea Italica (Broccoli) Extract, Oenothera Biennis (Evening Primrose) Flower Extract, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Pueraria Lobata Root Extract, Bambusa Vulgaris (Bamboo) Leaf Extract, Oldenlandia Diffusa Extract, Lonicera Caprifolium (Honeysuckle) Extract, Faex Extract, Limonia Acidissima Extract, Boswellia Serrata Resin Extract, Artemisia Capillaris Extract, Olea Europaea (Olive) Fruit Extract, Medicago Sativa (Alfalfa) Extract, Brassica Oleracea Capitata (Cabbage) Leaf Extract, Triticum Vulgare Germ Extract, Castanea Crenata (Chestnut) Shell Extract, Brassica Campestris (Rapeseed) Extract, Raphanus Sativus (Radish) Root Extract, Hydroxyethyl Cellulose, Disodium Edta, Caprylyl Glycol" },
  "GVS-255293": { description: "<p>Čisticí polštářky Dr.Althea s 2 % kyseliny salicylové, určené pro mastnou a problematickou pleť. Kyselina salicylová a kyselina mléčná jemně exfoliují, kyselina hyaluronová hydratuje a pleť zklidňují měsíček, vilín a čajovník. Polštářky můžete použít i lokálně na problémová místa.</p><ul><li>2 % kyselina salicylová</li><li>vhodné jako první krok po čištění</li><li>nepoužívejte na poškozenou pokožku</li></ul><p><strong>Použití:</strong> po očištění jemně přetřete celý obličej mimo oční okolí, nebo přiložte na problémová místa na 5–10 minut. Zbylou esenci vklepejte do pleti. Při začátku doporučujeme používat několikrát týdně.</p>" },
  "GVS-257020": { description: "<p>Krém Dr.Althea Melaclear Cream je cílená péče o pigmentové skvrny, stopy po akné a nerovnoměrný tón pleti. Kombinuje kyselinu tranexamovou, alfa-arbutin a niacinamid, ceramid NP podporuje hydrataci a bariéru. Textura se rozpouští v lehké krémové sérum a dá se používat lokálně nebo jako noční maska.</p><ul><li>pomáhá zesvětlit vzhled tmavých skvrn a vyrovnat tón pleti</li><li>lokální péče nebo celonoční maska</li><li>obsahuje ceramid NP</li></ul>" },
  "GVS-256221": { description: "<p>Lehký denní krém Dr.Althea 345 Relief Cream pro aknózní, citlivou a smíšenou pleť s následky po akné – zarudnutím, nerovnou strukturou nebo skvrnami. Niacinamid rozjasňuje, ceramid NP dlouhodobě hydratuje a pomáhá obnovit narušenou ochrannou bariéru, aniž by pleť zatížil. Krém je testován na citlivé pleti a nekomedogenní.</p><ul><li>objem 50 ml</li><li>zklidnění a hydratace pleti po akné</li><li>lehká, nemastná textura</li></ul>" },
  "GVS-14849": { description: "<p>Proteinová regenerační maska na vlasy CP-1 Keratin Intensive Fill-up od Esthetic House. Je určená pro vlasy namáhané barvením a tepelným stylingem. Keratin vyhlazuje kutikulu, patentovaný komplex Aquarich (extrakt z černého ovsa s lecitinem) tvoří ochrannou bariéru proti vysušení a hydrolyzovaný kolagen s proteiny vlasy zpevňují a dodávají jim lesk. Maska voní sladce květinově.</p><ul><li>objem 200 ml</li><li>pro poškozené, barvené a krepovité vlasy</li><li>vyhlazuje, zvláčňuje a omezuje třepení konečků</li></ul><p>Aplikujte po umytí šamponem na vlhké vlasy, nechte krátce působit a opláchněte (viz návod na obalu).</p>" },
  "GVS-256658": { description: "<p>Oční sérum Dr.Althea Retinol Flat Iron Eye Roller se zabudovaným masážním válečkem gua sha, který zvýrazňuje liftingový efekt a nedráždí oční okolí. Obsahuje 1 000 ppm retinolu a bakuchiol pro vyhlazení vrásek, kyselinu hyaluronovou pro hydrataci a 5 % Cica Retisome s centellou a madekasosidem, které zklidňují pokožku.</p><ul><li>retinol a bakuchiol v jedné formuli</li><li>veganské, bez umělého barviva</li><li>aplikátor s válečkem – masáž bez rukou</li></ul><p>Obsahuje retinol: doporučujeme používat spíše večer a přes den chránit pleť krémem s SPF.</p>" },
};

async function main() {
  let updated = 0;
  for (const [code, t] of Object.entries(TEXTS)) {
    const product = await prisma.product.findUnique({ where: { code }, select: { id: true, name: true, description: true } });
    if (!product) {
      console.log(`  [skip] not found: ${code}`);
      continue;
    }
    console.log(`  ${code} ${product.name.slice(0, 45)}: ${(product.description ?? "").length} -> ${t.description.length} chars${t.ingredients ? " + INCI" : ""}`);
    if (DRY_RUN) continue;
    await prisma.product.update({ where: { id: product.id }, data: { description: t.description, ...(t.ingredients ? { ingredients: t.ingredients } : {}) } });
    updated++;
  }
  if (!DRY_RUN && updated > 0) {
    await logAdminActivity({ action: "product.gvs_descriptions", entityType: "Product", detail: `GVS: Czech descriptions written for ${updated} products` });
  }
  console.log(`\nDone. ${updated} updated.`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
