ALTER TABLE "Settings" ADD COLUMN "shippingCostZasilkovna" DECIMAL(10,2) NOT NULL DEFAULT 79;
ALTER TABLE "Settings" ADD COLUMN "shippingCostPpl" DECIMAL(10,2) NOT NULL DEFAULT 90;
ALTER TABLE "Settings" ADD COLUMN "shippingCostDpd" DECIMAL(10,2) NOT NULL DEFAULT 99;
ALTER TABLE "Settings" ADD COLUMN "shippingCostBalikovna" DECIMAL(10,2) NOT NULL DEFAULT 69;
ALTER TABLE "Settings" ADD COLUMN "shippingCostGls" DECIMAL(10,2) NOT NULL DEFAULT 99;
ALTER TABLE "Settings" ADD COLUMN "shippingCostGlsMisto" DECIMAL(10,2) NOT NULL DEFAULT 54.45;
